// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9tfALU_fROPDVQXkQyS0VDETjukPlv0g',
    appId: '1:372689824242:web:5fe5d020262ca8e0ec636b',
    messagingSenderId: '372689824242',
    projectId: 'ai-65448',
    authDomain: 'ai-65448.firebaseapp.com',
    storageBucket: 'ai-65448.appspot.com',
    measurementId: 'G-47GKLLPHVM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJBmHK3e7wPiFQgYCoVzBC8T-9Gki5818',
    appId: '1:372689824242:android:a4471d353a3ccfd7ec636b',
    messagingSenderId: '372689824242',
    projectId: 'ai-65448',
    storageBucket: 'ai-65448.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAs56cVSrrilvz7IOIAiQXHUNfV4VZCcBo',
    appId: '1:372689824242:ios:fb0fff779f645b8eec636b',
    messagingSenderId: '372689824242',
    projectId: 'ai-65448',
    storageBucket: 'ai-65448.appspot.com',
    iosBundleId: 'com.example.aihqAnalytics',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAs56cVSrrilvz7IOIAiQXHUNfV4VZCcBo',
    appId: '1:372689824242:ios:bc0e34ead0738e02ec636b',
    messagingSenderId: '372689824242',
    projectId: 'ai-65448',
    storageBucket: 'ai-65448.appspot.com',
    iosBundleId: 'com.example.aihqAnalytics.RunnerTests',
  );
}
